export const currentUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  image: "/avatars/john-doe.png",
  isPro: true,
}

export const itemTypes = [
  { id: "type_snippet", name: "snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_note", name: "note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_file", name: "file", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "image", icon: "Image", color: "#ec4899", isSystem: true },
  { id: "type_link", name: "link", icon: "Link", color: "#10b981", isSystem: true },
]

export const collections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    defaultTypeId: "type_snippet",
    createdAt: new Date("2026-01-10"),
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    defaultTypeId: "type_snippet",
    createdAt: new Date("2026-01-12"),
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    defaultTypeId: "type_prompt",
    createdAt: new Date("2026-01-08"),
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    defaultTypeId: "type_note",
    createdAt: new Date("2026-01-05"),
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    defaultTypeId: "type_command",
    createdAt: new Date("2026-01-03"),
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    defaultTypeId: "type_prompt",
    createdAt: new Date("2026-01-15"),
  },
]

export const tags = [
  { id: "tag_1", name: "react" },
  { id: "tag_2", name: "auth" },
  { id: "tag_3", name: "hooks" },
  { id: "tag_4", name: "api" },
  { id: "tag_5", name: "error-handling" },
  { id: "tag_6", name: "python" },
  { id: "tag_7", name: "git" },
  { id: "tag_8", name: "ai" },
  { id: "tag_9", name: "typescript" },
  { id: "tag_10", name: "nextjs" },
  { id: "tag_11", name: "css" },
  { id: "tag_12", name: "database" },
]

export const items = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "text",
    content: "export function useAuth() { ... }",
    description: "Custom authentication hook for React applications",
    isFavorite: true,
    isPinned: true,
    language: "typescript",
    itemTypeId: "type_snippet",
    createdAt: new Date("2026-01-15"),
    tagIds: ["tag_1", "tag_2", "tag_3"],
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "text",
    content: "async function fetchWithRetry(url, options) { ... }",
    description: "Fetch wrapper with exponential backoff retry logic",
    isFavorite: false,
    isPinned: true,
    language: "typescript",
    itemTypeId: "type_snippet",
    createdAt: new Date("2026-01-12"),
    tagIds: ["tag_4", "tag_5"],
  },
  {
    id: "item_3",
    title: "Debounce Hook",
    contentType: "text",
    content: "export function useDebounce(value, delay) { ... }",
    description: "React hook for debouncing values",
    isFavorite: false,
    isPinned: false,
    language: "typescript",
    itemTypeId: "type_snippet",
    createdAt: new Date("2026-01-14"),
    tagIds: ["tag_1", "tag_3", "tag_9"],
  },
  {
    id: "item_4",
    title: "List Comprehension Patterns",
    contentType: "text",
    content: "[x**2 for x in range(10) if x % 2 == 0]",
    description: "Common Python list comprehension patterns",
    isFavorite: false,
    isPinned: false,
    language: "python",
    itemTypeId: "type_snippet",
    createdAt: new Date("2026-01-13"),
    tagIds: ["tag_6"],
  },
  {
    id: "item_5",
    title: "Project Context Template",
    contentType: "text",
    content: "# Project Overview\n\n## Stack\n## Architecture\n## Conventions",
    description: "AI context file template for new projects",
    isFavorite: true,
    isPinned: false,
    language: "markdown",
    itemTypeId: "type_prompt",
    createdAt: new Date("2026-01-11"),
    tagIds: ["tag_8", "tag_10"],
  },
  {
    id: "item_6",
    title: "System Design Cheat Sheet",
    contentType: "text",
    content: "# System Design\n\n## Load Balancers\n## Caching\n## Database Sharding",
    description: "Key system design concepts for interviews",
    isFavorite: false,
    isPinned: false,
    language: "markdown",
    itemTypeId: "type_note",
    createdAt: new Date("2026-01-10"),
    tagIds: [],
  },
  {
    id: "item_7",
    title: "Git Rebase Workflow",
    contentType: "text",
    content: "git checkout main\ngit pull\ngit checkout feature\ngit rebase main",
    description: "Clean git rebase workflow for feature branches",
    isFavorite: true,
    isPinned: false,
    language: "bash",
    itemTypeId: "type_command",
    createdAt: new Date("2026-01-09"),
    tagIds: ["tag_7"],
  },
  {
    id: "item_8",
    title: "React + TypeScript Setup Prompt",
    contentType: "text",
    content: "You are an expert React and TypeScript developer...",
    description: "System prompt for setting up a React + TypeScript project",
    isFavorite: false,
    isPinned: false,
    language: "text",
    itemTypeId: "type_prompt",
    createdAt: new Date("2026-01-08"),
    tagIds: ["tag_8", "tag_1", "tag_9"],
  },
  {
    id: "item_9",
    title: "CSS Grid Layouts",
    contentType: "text",
    content: ".grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem; }",
    description: "Common CSS Grid patterns for layouts",
    isFavorite: false,
    isPinned: false,
    language: "css",
    itemTypeId: "type_snippet",
    createdAt: new Date("2026-01-07"),
    tagIds: ["tag_11"],
  },
  {
    id: "item_10",
    title: "Prisma Query Patterns",
    contentType: "text",
    content: "const users = await prisma.user.findMany({ include: { posts: true } })",
    description: "Common Prisma ORM query patterns",
    isFavorite: false,
    isPinned: false,
    language: "typescript",
    itemTypeId: "type_snippet",
    createdAt: new Date("2026-01-06"),
    tagIds: ["tag_12", "tag_9", "tag_10"],
  },
  {
    id: "item_11",
    title: "Code Review Checklist",
    contentType: "text",
    content: "- [ ] Error handling\n- [ ] Edge cases\n- [ ] Performance",
    description: "Checklist for reviewing pull requests",
    isFavorite: false,
    isPinned: false,
    language: "markdown",
    itemTypeId: "type_note",
    createdAt: new Date("2026-01-05"),
    tagIds: [],
  },
  {
    id: "item_12",
    title: "Tailwind Cheat Sheet",
    contentType: "url",
    content: null,
    description: "Quick reference for Tailwind CSS utility classes",
    url: "https://tailwindcss.com/docs/cheat-sheet",
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: "type_link",
    createdAt: new Date("2026-01-04"),
    tagIds: ["tag_11"],
  },
  {
    id: "item_13",
    title: "React Documentation",
    contentType: "url",
    content: null,
    description: "Official React documentation",
    url: "https://react.dev",
    isFavorite: false,
    isPinned: false,
    language: null,
    itemTypeId: "type_link",
    createdAt: new Date("2026-01-03"),
    tagIds: ["tag_1"],
  },
  {
    id: "item_14",
    title: "Next.js Project Setup",
    contentType: "text",
    content: "npx create-next-app@latest my-app --typescript --tailwind --eslint",
    description: "Command to scaffold a new Next.js project",
    isFavorite: false,
    isPinned: false,
    language: "bash",
    itemTypeId: "type_command",
    createdAt: new Date("2026-01-02"),
    tagIds: ["tag_10", "tag_9"],
  },
  {
    id: "item_15",
    title: "Git Commit Convention",
    contentType: "text",
    content: "feat: add user authentication\nfix: resolve login redirect loop",
    description: "Conventional commit format for git history",
    isFavorite: false,
    isPinned: false,
    language: "text",
    itemTypeId: "type_command",
    createdAt: new Date("2026-01-01"),
    tagIds: ["tag_7"],
  },
]

export const itemCollections = [
  { itemId: "item_1", collectionId: "col_1" },
  { itemId: "item_3", collectionId: "col_1" },
  { itemId: "item_10", collectionId: "col_1" },
  { itemId: "item_9", collectionId: "col_1" },
  { itemId: "item_4", collectionId: "col_2" },
  { itemId: "item_5", collectionId: "col_3" },
  { itemId: "item_8", collectionId: "col_3" },
  { itemId: "item_6", collectionId: "col_4" },
  { itemId: "item_11", collectionId: "col_4" },
  { itemId: "item_7", collectionId: "col_5" },
  { itemId: "item_14", collectionId: "col_5" },
  { itemId: "item_15", collectionId: "col_5" },
  { itemId: "item_5", collectionId: "col_6" },
  { itemId: "item_8", collectionId: "col_6" },
]
